//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuStripGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripGradientBegin"]));
            }
            set {
                this["MenuStripGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color MenuStripGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripGradientEnd"]));
            }
            set {
                this["MenuStripGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color MenuStripForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripForeColor"]));
            }
            set {
                this["MenuStripForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color MenuItemPressedGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemPressedGradientBegin"]));
            }
            set {
                this["MenuItemPressedGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color MenuItemPressedGradientMiddle {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemPressedGradientMiddle"]));
            }
            set {
                this["MenuItemPressedGradientMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color MenuItemPressedGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemPressedGradientEnd"]));
            }
            set {
                this["MenuItemPressedGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelectedGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemSelectedGradientBegin"]));
            }
            set {
                this["MenuItemSelectedGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelectedGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemSelectedGradientEnd"]));
            }
            set {
                this["MenuItemSelectedGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemSelected {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemSelected"]));
            }
            set {
                this["MenuItemSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color ImageMarginGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["ImageMarginGradientBegin"]));
            }
            set {
                this["ImageMarginGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ImageMarginGradientMiddle {
            get {
                return ((global::System.Drawing.Color)(this["ImageMarginGradientMiddle"]));
            }
            set {
                this["ImageMarginGradientMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ImageMarginGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["ImageMarginGradientEnd"]));
            }
            set {
                this["ImageMarginGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuBorder {
            get {
                return ((global::System.Drawing.Color)(this["MenuBorder"]));
            }
            set {
                this["MenuBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuItemBorder {
            get {
                return ((global::System.Drawing.Color)(this["MenuItemBorder"]));
            }
            set {
                this["MenuItemBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ToolStripBorder {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripBorder"]));
            }
            set {
                this["ToolStripBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ToolStripContentPanelGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripContentPanelGradientBegin"]));
            }
            set {
                this["ToolStripContentPanelGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripContentPanelGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripContentPanelGradientEnd"]));
            }
            set {
                this["ToolStripContentPanelGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripDropDownBackground {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripDropDownBackground"]));
            }
            set {
                this["ToolStripDropDownBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ToolStripGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripGradientBegin"]));
            }
            set {
                this["ToolStripGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ToolStripGradientMiddle {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripGradientMiddle"]));
            }
            set {
                this["ToolStripGradientMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ToolStripGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripGradientEnd"]));
            }
            set {
                this["ToolStripGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color StatusStripGradientBegin {
            get {
                return ((global::System.Drawing.Color)(this["StatusStripGradientBegin"]));
            }
            set {
                this["StatusStripGradientBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color StatusStripGradientEnd {
            get {
                return ((global::System.Drawing.Color)(this["StatusStripGradientEnd"]));
            }
            set {
                this["StatusStripGradientEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ToolStripForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ToolStripForeColor"]));
            }
            set {
                this["ToolStripForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color StatusStripForeColor {
            get {
                return ((global::System.Drawing.Color)(this["StatusStripForeColor"]));
            }
            set {
                this["StatusStripForeColor"] = value;
            }
        }
    }
}
