//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapefileEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapefileEditor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Vertices.
        /// </summary>
        internal static string mnuShowVertices {
            get {
                return ResourceManager.GetString("mnuShowVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapefile Editor.
        /// </summary>
        internal static string mnuShpEditor {
            get {
                return ResourceManager.GetString("mnuShpEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to All Layers.
        /// </summary>
        internal static string mnuSnapToAllLayers {
            get {
                return ResourceManager.GetString("mnuSnapToAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to Vertices.
        /// </summary>
        internal static string mnuSnapToVertices {
            get {
                return ResourceManager.GetString("mnuSnapToVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in Add Mode when Adding.
        /// </summary>
        internal static string mnuStayInAddMode {
            get {
                return ResourceManager.GetString("mnuStayInAddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new regular shape to current shapefile.
        /// </summary>
        internal static string tooltipAddRegularShp {
            get {
                return ResourceManager.GetString("tooltipAddRegularShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new shape to current shapefile.
        /// </summary>
        internal static string tooltipAddShp {
            get {
                return ResourceManager.GetString("tooltipAddShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a vertex to an existing shape.
        /// </summary>
        internal static string tooltipAddVertex {
            get {
                return ResourceManager.GetString("tooltipAddVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check and clean up the shapefile.
        /// </summary>
        internal static string tooltipCheckCleanShp {
            get {
                return ResourceManager.GetString("tooltipCheckCleanShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected shape to the clipboard.
        /// </summary>
        internal static string tooltipCopyShpToClipboard {
            get {
                return ResourceManager.GetString("tooltipCopyShpToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new shapefile.
        /// </summary>
        internal static string tooltipCreateShp {
            get {
                return ResourceManager.GetString("tooltipCreateShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Undo Capability.
        /// </summary>
        internal static string tooltipDisableUndo {
            get {
                return ResourceManager.GetString("tooltipDisableUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Undo Capability.
        /// </summary>
        internal static string tooltipEnableUndo {
            get {
                return ResourceManager.GetString("tooltipEnableUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase current layer beneath the selected Shape.
        /// </summary>
        internal static string tooltipEraseLayerBeneathShp {
            get {
                return ResourceManager.GetString("tooltipEraseLayerBeneathShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase current layer at selected Shape.
        /// </summary>
        internal static string tooltipEraseLayerShp {
            get {
                return ResourceManager.GetString("tooltipEraseLayerShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Two Shapes.
        /// </summary>
        internal static string tooltipMergeShp {
            get {
                return ResourceManager.GetString("tooltipMergeShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move existing shapes in selected layer.
        /// </summary>
        internal static string tooltipMoveShp {
            get {
                return ResourceManager.GetString("tooltipMoveShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move an existing vertex in a shape.
        /// </summary>
        internal static string tooltipMoveVertex {
            get {
                return ResourceManager.GetString("tooltipMoveVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a shape from the clipboard.
        /// </summary>
        internal static string tooltipPasteShpFromClipboard {
            get {
                return ResourceManager.GetString("tooltipPasteShpFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shape from current shapefile.
        /// </summary>
        internal static string tooltipRemoveShp {
            get {
                return ResourceManager.GetString("tooltipRemoveShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a vertex from an existing shape.
        /// </summary>
        internal static string tooltipRemoveVertex {
            get {
                return ResourceManager.GetString("tooltipRemoveVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize (expand or shrink) a shape.
        /// </summary>
        internal static string tooltipResizeShp {
            get {
                return ResourceManager.GetString("tooltipResizeShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate a shape about its centroid or a specified point.
        /// </summary>
        internal static string tooltipRotateShp {
            get {
                return ResourceManager.GetString("tooltipRotateShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Options.
        /// </summary>
        internal static string tooltipUndo {
            get {
                return ResourceManager.GetString("tooltipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Last Change.
        /// </summary>
        internal static string tooltipUndoLastChange {
            get {
                return ResourceManager.GetString("tooltipUndoLastChange", resourceCulture);
            }
        }
    }
}
